### ISSUE TITLE
puni-kill-line operating on an expression spanning multiple lines does not include semicolon

### ISSUE THREAD

**Issue by terlar** [AmaiKinono/puni#15]
I explored this a bit and find it a bit inconsistent, I guess it is related how newline is used when working on a single line vs an expression spanning multiple lines.

If you have some JavaScript code like this:
```
{ hello: "world" };
```

With cursor at beginning of line (represented by `|`) running `puni-kill-line`:
```
|{ hello: "world" };
```

You will end up with this:
```
|
```

However, if you have the following JavaScript code:
```
{
  hello: "world",
};
```

With cursor at beginning of line (represented by `|`) running `puni-kill-line`:
```
|{
  hello: "world",
};
```

You will end up with this:
```
|;
```

When using `forward-sexp` cursor will end up just before `;` in both cases, but using `puni-kill-line` the single line case will follow the preferred outcome and also remove the semicolon.

**Comment by AmaiKinono** [comment]
That's what I expect when I press `C-k`. I want it to kill one line, or one multiline sexp.

e.g.

```
|(foo
  bar) (baz)
;; what I expect `puni-kill-line` to do:
| (baz)
```

Maybe the name of the command is misleading or I didn't put it clearly in the docstring...

**Comment by terlar** [comment]
I see, that makes sense, I guess that is just one unfortunate case with those languages that use semicolon at the end of lines. It was just one of those things that I thought was as it should but hoped there might be a way around it. But I guess there is no way without special casing it.
