### ISSUE TITLE
Inserting comment character easily breaks balance

### ISSUE THREAD

**Issue by tsdh** [AmaiKinono/puni#17]
With a minimal example sexp like `(foo)` one can easily break balance by just inserting a `comment-start` character after `foo`.  Likewise, with a multi-line sexp like
```elisp
(foo
  bar)
```
one can easily break balance by inserting a `comment-start` before `(foo`.

With paredit, the first action results in
```elisp
(foo;|
 )
```
and the second in
```elisp
;|
(foo
 bar)
```
where | denotes the position of point, i.e., it inserts `comment-start` plus a newline in order to preserve balance.  paredit allows only commenting out a complete sexp which is on one line or a region.  In the latter case, the user is responsible of keeping balance.

That issue can also be demonstrated with non-lisp languages.  For example, `sh-mode` is based on SMIE and therefore shell script constructs can be treated as sexps.

```sh
if [ -f foo.txt ]; then
    do-stuff
fi
do-more-stuff
```
In that example, inserting a `#` before `then` or `fi` introduces balance breakage.

**Comment by AmaiKinono** [comment]
I don't consider this to be a bug.

- Usually we know where to put our comment. Even if we start a comment by mistake, we can undo it.
- To me, ParEdit is doing too much. I need to be very familiar with it to predict the behavior.

It's not easy to implement, too. ParEdit binds `;` to `paredit-semicolon`. It's easy to do that for Lisp, but other languages use different chars for comment.

**Comment by tsdh** [comment]
That's fine by me.  I just need to train my muscle memory a bit. ;-)
