### ISSUE TITLE
Spacing around keywords that would be parentheses in lisp

### ISSUE THREAD

**Issue by tsdh** [AmaiKinono/puni#18]
SMIE-based modes such as `sh-mode` work extremely well with sexp-based motion and are therefore very suitable for puni, too.  However, in contrast to lisp where parentheses surround lists, other languages use keywords which have different whitespace requirements, especially, they must be surrounded by whitespace in order to make sense.

Take this shell example where | denotes the position of point:
```sh
if [ -f foo.txt ]; then
    |do-stuff
fi
do-more-stuff
```
When I do `puni-slurp-forward` in order to include `do-more-stuff` in the "then ... fi"-sexp, I'll end up with the invalid
```sh
if [ -f foo.txt ]; then
    do-stuff

    do-more-stufffi
```
where the `fi` is concatenated with `do-mode-stuff`.  (BTW, why is there a newline added after `do-stuff`?)

Ideally, I'd like to get
```sh
if [ -f foo.txt ]; then
    do-stuff
    do-more-stuff
fi
```
So I guess in non-lisp languages, puni somehow needs to ensure that the "list start and end thingy" are surrounded by some form of whitespace.  I think the correct whitespace is the one which already was before that element, so `\n` in the above example.

**Comment by AmaiKinono** [comment]
Thanks for the report. I only tested on Lisp when creating those commands. I'll inspect it in a few days.

**Comment by tsdh** [comment]
Thanks, I've given it a quick try in a `sh-mode` buffer and it seems to work fine.  Very cool, thanks!

**Comment by bymoz089** [comment]
with current solution, the valid (bad style) code of

    if [ foo ]; then
        bar ; |fi
    baz

results in

    if [ foo ]; then
        bar ;|
        baz fi

which is then invalid

end delimiters in bash need either an `;` or an  `newline`

**Comment by AmaiKinono** [comment]
> Could it be an solution to introduce a customizeable variable which consists of a plist, with languages which need some extras for their delimiters?

Personally I am against this.

- I myself don't use slurp/barf in non-Lisp languages.
- In non-Lisp languages, I can't imagine people using slurp/barf in non-obvious situations. So the benefit is not obvious.
- As far as I can tell, the option proposed does not fit in Puni's framework. The code of Puni is basically build on heuristics, and it's extremely important to keep it in a unified shape so it could still be maintained.

**Comment by AmaiKinono** [comment]
> Could it be an solution to introduce a customizeable variable which consists of a plist, with languages which need some extras for their delimiters?

Personally I am against this.

- I myself don't use slurp/barf in non-Lisp languages.
- In non-Lisp languages, I can't imagine people using slurp/barf in non-obvious situations. So the benefit is not obvious.
- As far as I can tell, the option proposed does not fit in Puni's framework. The code of Puni is basically build on heuristics, and it's extremely important to keep it in a unified shape so it could still be maintained.
