### ISSUE TITLE
puni-backward-delete-char should splice when the list around point is empty

### ISSUE THREAD

**Issue by daanturo** [AmaiKinono/puni#21]
Instead of not doing anything, `puni-backward-delete-char` should splice the sexp around point when the delimiters are next to each other.

```lisp
(|)
;; calls `puni-backward-delete-char`

;; Observed:
|()

;; Expected:
|
```

Currently, `puni-mode-map` doesn't provide any key bindings to delete the pair, the shortest I have found (without additional bindings) is `backspace delete delete`: 3 key presses.

**Comment by daanturo** [comment]
Yes, I think that the behavior for multi-char delimiters is debatable and hard to define correctly, too. So let's limit it for now.

**Comment by AmaiKinono** [comment]
I've modified it a bit and it now it deals with the multi-char delimiter case. This is because I do like it, and by switching the order of conditional branches, the `if|fi` problem is gone.
