### ISSUE TITLE
two convenience functions for delete and splice

### ISSUE THREAD

**Issue by bymoz089** [AmaiKinono/puni#24]
I missed some convenience functions. Those functions delete some content of the current sexp before splicing. Maybe it is possible to include them (or better versions of them)?

    (defun puni-splice-sexp-killing-backward ()
      "remove sexp content before point and splice."
      (interactive)
      (save-excursion
        (let ((pos (point)))
          (puni-beginning-of-sexp)
          (delete-region (point) pos)
          (puni-splice))))

    (defun puni-splice-sexp-killing-forward ()
      "remove sexp content after point and splice."
      (interactive)
      (save-excursion
        (let ((pos (point)))
          (puni-end-of-sexp)
          (delete-region pos (point))
          (puni-splice))))

**Comment by AmaiKinono** [comment]
You can do it by:

- `puni-kill-line(-backward)` then `puni-splice`
- Mark the region you want to keep, then `puni-raise`

I don't like to put such "composed" commands into Puni unless people really use them daily.

**Comment by bymoz089** [comment]
Thanks for responding and for mentioning `puni-kill-line`! Now the body of above functions have only two lines. It's ok to define that on a private config.

    (defun my-puni-splice-sexp-killing-backward ()
      (interactive)
      (puni-backward-kill-line)
      (puni-splice))

Would you consider to make the kill argument of `puni-soft-delete` a customizable option?         
I prefer to not pollute my `kill-ring` and therefore `adviced` `puni-soft-delete` to always operate with argument `kill` set to `nil`.

    (defun my-puni-soft-delete-filter-kill-arg (orig-fun from to &optional strict-sexp style kill fail-action return-region)
      (funcall orig-fun from to strict-sexp style nil fail-action return-region))
    (advice-add #'puni-soft-delete :around #'my-puni-soft-delete-filter-kill-arg)

(*note*: I gave the implementation of functions, just for documentation for future readers.)

**Comment by AmaiKinono** [comment]
Well, actually using `puni-kill-line` isn't a good idea. It can't deal with multi-line sexp:

```elisp
(foo|
 bar)
;; what you want for puni-splice-sexp-killing-forward
foo|
;; what it actually does
foo|bar
```

Your original implementation is quite clean. Seems you don't like to define complex commands in private config? Here's a two-line version:

```elisp
(defun puni-splice-sexp-killing-forward ()
  (interactive)
  (delete-region (point) (puni-end-of-list-around-point))
  (puni-splice))
```
