### ISSUE TITLE
Unhandled branch in Python mode

### ISSUE THREAD

**Issue by daanturo** [AmaiKinono/puni#25]
The whole relevant buffer in `python-mode`:
```python
n.
#
```
`puni-backward-delete-char` after `.`:
```
You’ve found an unhandled branch in Puni.
Direction: forward
beg: 2, end: 5, another-beg: 1, another-end: 3
```

**Comment by AmaiKinono** [comment]
Thanks for the report and sorry for my late reply.

It should be fixed, and after this fix, only very very corner cases could run into unhandled branch. Great news ;)
