### ISSUE TITLE
Should this be taking so long (latex-mode)

### ISSUE THREAD

**Issue by apc** [AmaiKinono/puni#26]
On my end, calling something like `puni-backward-delete-char` with point at the end of a line consisting just of a pair of braces (`{}`) takes *quite* a long time depending on the complexity of the file the buffer is visiting, sometimes more than 30 seconds. 

You could see if you get the same behavior for yourself by running an instance of vanilla Emacs, installing `puni`, and enabling `puni-global-mode` after visiting [the source for the Memoir manual](https://www.ctan.org/tex-archive/macros/latex/contrib/memoir/doc-src). In my system, Inserting a pair of braces at the end of the document and calling `puni-backward-delete-char` took a whooping 71.4 seconds. 

From what I can tell, what's taking this long is `puni-bounds-of-sexp-around-point`, but I do not understand well enough its definition to go any further. 

I don't know whether this means there's something wrong on my end. If not, I'd be curious to know how to get around this issue (assuming it's not a bug, but rather a consequence of the interaction of `puni` with complex `.tex` documents).

**Comment by AmaiKinono** [comment]
Sorry for the late response. This should be fixed but it reveals a `tex-mode` problem (I think).

Try `(while (puni-strict-backward-sexp))` or `(while (progn (backward-sexp) t))` at the end of `memman.tex`, the cursor can't go all the way back to the beginning of the file, but it should be as the file should contain several top-level balanced expressions. This problem eventually causes `puni-bounds-of-sexp-around-point` to be very slow.
