### ISSUE TITLE
How to disable puni-mode when iedit-mode or multiple cursor is active

### ISSUE THREAD

**Issue by QiangF** [AmaiKinono/puni#27]
Suppose puni-global-mode is nil. One way is to disable puni-mode in iedit-mode-hook and enable in iedit-mode-end-hook. What if puni-mode is not active in before entering iedit?

**Comment by AmaiKinono** [comment]
What I could think of is to define a new variable `puni-mode-enabled-before-iedit`. Set it in `iedit-mode-hook`, and check it in `iedit-mode-end-hook`.
