### ISSUE TITLE
Feature request: keep the mode specific binding for "DEL" if the previous char or chars not including part of a matching pair

### ISSUE THREAD

**Issue by QiangF** [AmaiKinono/puni#29]
In python mode buffer when puni-mode is enabled, we have:

    (define-key map (kbd "DEL") 'puni-backward-delete-char)
    
However, the default binding is python-indent-dedent-line-backspace, which is very useful to quickly get the indent level right.
There might be other places that puni-mode makes editing less efficient.
I wish in such cases puni should get out of the way, and only work if there is something it can do.

**Comment by AmaiKinono** [comment]
Commands shouldn't be coupled with keybindings. `DEL` is almost always meant to delete a char, but we shouldn't assume that as the user may customize it.

If you want the behavior you described, bind this to `DEL` in `puni-mode-map`:

```elisp
(defun my-backward-delete-char ()
  (interactive)
  (unless (bobp)
    (if (puni-region-balance-p  (1- (point)) (point))
        (unwind-protect
            (progn (puni-mode -1)
                   (execute-kbd-macro (kbd "DEL")))
          (puni-mode))
      (puni-backward-delete-char))))
```

You could put it in the wiki if you like ;)

**Comment by QiangF** [comment]
Thank you! A small modification to support numerical arguments.

     (defun my-puni-backward-delete-char (&optional n)
       (interactive "p")
       (unless (bobp)
         (setq n (or n 1))
         (if (puni-region-balance-p (- (point) n) (point))
             (unwind-protect (progn (puni-mode -1)
                                    (execute-kbd-macro (kbd "DEL") n))
               (puni-mode))
             (puni-backward-delete-char n))))
