### ISSUE TITLE
Allow C-w to work on whole line or region

### ISSUE THREAD

**Issue by terlar** [AmaiKinono/puni#3]
I have been a user of [whole-line-or-region](https://github.com/purcell/whole-line-or-region) for some time and missed that feature when I enable `puni-mode`. As then `C-w` gets overridden by puni and then it won’t work without selection.

It would be great if an option was available to make `C-w` work on the whole line if no region was selected. Or if it was the default behavior.

Thanks for the package, I’m looking to replace smartparens with this, as I don’t like to tweak the deletion logic for each new major mode. But have really gotten used to have the strict mode that lets me use just a small set of commands to do my editing while coding.

**Comment by AmaiKinono** [comment]
I have to confirm, did you really mean deleting the whole line?

Puni is all about soft deletion, while a line could be an incomplete/unbalanced expression. So with your design, pressing `C-w` could easily mess up the parentheses.

I think a better action when no active region is goto the start of the line, and call `puni-kill-line`. What do you think?

Also, do you know Elisp? Puni encourages the user to define their own commands (in fact, Puni comes from several of my own commands). If you do, then I don't have to write it for you ;)

**Comment by terlar** [comment]
Sorry if I was unclear. The ideal case would be to keep the puni behavior, but act like whole line or region.

So I guess `C-w` without any region would execute `move-beginning-of-line` and then `puni-kill-line`.
I think that is a good idea.

Yes, I know Elisp. I thought it was a nice default though, since `C-w` without a region does nothing by default. But since it is not default behavior in Emacs I guess either having it behind a variable or just in my own config,

I haven't looked into the source code of `puni` yet. But I guess I would bind my own key to `C-w` instead of `puni-kill-active-region`?

**Comment by AmaiKinono** [comment]
You have to create your own command for that.

People have different ideas about "nice default behavior". If we introduce one user option for this, soon we'll have a hundred of them.

You could look into the implementation of `puni-delete-active-region`, and change the logic when there's no active region. Since it actually signals an error, you could also advise around it to catch the error, or deal with the situation when there's no active region before calling it... There are many ways.

**Comment by terlar** [comment]
Fair enough, I will close this then and try to put this in my own config.

Thanks for your information and help.
