### ISSUE TITLE
awkward whitespace handling on slurp-forward

### ISSUE THREAD

**Issue by bymoz089** [AmaiKinono/puni#30]
Whitespace handling in lisp-*-mode, when doing `puni-slurp-forward` is awkward.

Example: 

    (foo |)bar

doing `puni-slurp-forward` results in

    (foo|bar )

expected (and know from older versions) behavior is:

    (foo |bar)

Tested with `emacs -Q` version 28 and puni most recent version as of 2022.June.08.

**Comment by AmaiKinono** [comment]
The spaces before the ending delimiter is seen as part of the delimiter. This is for solving #18. I need to experiment a bit to know if we can handle both #18 and the situation you described.

**Comment by AmaiKinono** [comment]
Should be fixed. Please test.

**Comment by bymoz089** [comment]
Thank you. Yes it is fixed, I could not find an issue.
