### ISSUE TITLE
Make pulse-region calls optional

### ISSUE THREAD

**Issue by vizs** [AmaiKinono/puni#31]
Good day, Hao!

Currently, there's no user option to turn off the pulse region calls in paredit-slurp,barf,splice.  Can you add such an option please?  My rationale for that is it is distracting when you have the pulse-flag set to nil.

**Comment by AmaiKinono** [comment]
I've added `puni-blink-for-slurp-barf`.

**Comment by vizs** [comment]
Thanks!
