### ISSUE TITLE
Custom keybindings does not get loaded

### ISSUE THREAD

**Issue by alternateved** [AmaiKinono/puni#32]
Hello!

As noted in the README:
```
;; The autoloads of Puni are set up so you can enable `puni-mode` or
;; `puni-global-mode` before `puni` is actually loaded. Only after you press
;; any key that calls Puni commands, it's loaded.
```
What in situation when one would want to define custom keybindings? I have a couple of bindings defined like so:
```lisp
(eval-after-load 'puni
  #'(lambda nil
      (progn
        (define-key puni-mode-map
                    [C-up]
                    #'puni-raise)
        (define-key puni-mode-map
                    [C-down]
                    #'puni-splice)
        (define-key puni-mode-map
                    [C-right]
                    #'puni-slurp-forward)
        (define-key puni-mode-map
                    [C-left]
                    #'puni-barf-forward))))
```
It seems that those won't get loaded until I use some other puni binding like `puni-kill-line`. Is there a way to work around that?                     

Kind wishes,
alternateved

**Comment by AmaiKinono** [comment]
I think just remove the `with-eval-after-load` wrapper would make things work.

**Comment by alternateved** [comment]
Ah right! I feel stupid for asking such a question. Without `with-eval-after-load` it works.

**Comment by AmaiKinono** [comment]
Great ;) I'll close the issue then.
