### ISSUE TITLE
[Suggestion] add support for shift selections (marking) for some puni operations

### ISSUE THREAD

**Issue by Inc0n** [AmaiKinono/puni#35]
`(interactive "^")` allow a command to be marking if the keybind of that command is activated with a shift key pressed, if `shift-select-mode` is activated.

So as of now, C-M-S-f (puni-forward-sexp) would not mark anything but to move cursor a sexp worth forward.
This addition would allow the region to be marked also, this can be convenient feature to be added in.

The puni commands that could benefit from this, I would think:
- puni-forward-sexp
- puni-backward-sexp
- puni-end-of-sexp
- puni-beginning-of-sexp

**Comment by AmaiKinono** [comment]
Close by #37.
