### ISSUE TITLE
`puni-global-mode` breaks `calc`

### ISSUE THREAD

**Issue by tsdh** [AmaiKinono/puni#36]
In the builtin emacs calculator `calc`, one can usually delete the last stack entry using both `<backspace>` and `<delete>` (the command bound to these keys is `calc-pop`).

When `puni-global-mode` is active and thus `puni-mode` is activated in every buffer including the calc buffer, `<backspace>` becomes `puni-backward-delete-char` which just signals an error that the buffer is read-only.

Not sure how to deal with the issue.  Probably there needs to be some customizable variable being a list of predicates which are run on the buffer in question and if one returns non-nil, `puni-mode` activation is inhibited.  A likely predicate for such a list would be `(lambda () (derived-mode-p 'special-mode))` where unfortunately `calc-mode` is so old that it's not defined in terms of `define-derived-mode` but adding a `(lambda () (derived-mode-p 'special-mode 'calc-mode))` will do.

**Comment by AmaiKinono** [comment]
What about

```elisp
(add-hook 'calc-mode-hook #'puni-disable-puni-mode)
```

? It's in the readme.

**Comment by tsdh** [comment]
Oh, I'm sorry.  I have missed that.
