### ISSUE TITLE
puni-splice doesn't unescape strings, barf/slurp doesn't (un)escape strings

### ISSUE THREAD

**Issue by andreyorst** [AmaiKinono/puni#41]
When point is inside of the string, calling `puni-splice` removes quotes, but leaves escaped quotes in their original form. For example:

```
"foo| \"bar\" baz"
=>
foo| \"bar\" baz
```

Smartparens and Paredit, however, unescape the string:

```
"foo| \"bar\" baz"
=>
foo| "bar" baz
```

Slurping and barfing has a similar issue:

```
"foo|" "bar" ; puni-slurp-forward
=>
"foo| "bar""
```

Paredit will do the following:

```
"foo|" "bar" ; paredit-forward-slurp-sexp
=>
"foo| \"bar\""
```

Smartparens just joins strings:

```
"foo|" "bar" ; sp-forward-slurp-sexp
=>
"foo| bar"
```

Proposal: Rework `puni-splice` to understand strings, and teach slurp/barf commands to (un)escape strings when moving quotes around.

**Comment by andreyorst** [comment]
Escaping strings should probably be as easy as using the `(format "%S" str)`, e.g. I had my own implementation some time ago that did it like that: https://github.com/andreyorst/dotfiles/blob/5118e794ac82a186762b3397a7e230725e2b9491/.config/emacs/init.el#L281-L313

As far as I can see, all there's needed to be done is using `(format "%S" str)` when moving quotes forward, and substituting `\\` to nothing when moving quotes backward. Probably, that is.

**Comment by AmaiKinono** [comment]
I'm not sure. Implementing this seems to add a lot of complexity.

It's worth doing if it's common to manipulating strings using these commands, but if we rarely do this, it's not a big deal to have to manually fix the result.

I actually don't use the sexp-manipulating commands often, and I can't imagine people using them on strings often.

**Comment by andreyorst** [comment]
no problem, I'll probably just fix this for myself for now then, thanks!
