### ISSUE TITLE
puni-kill-line removing the indentation after deleting empty lines

### ISSUE THREAD

**Issue by vifon** [AmaiKinono/puni#44]
Hello. I've noticed the following behavior in `puni-kill-line`:

```elisp
(foo bar
|
     baz)
;; call `puni-kill-line'
(foo bar
|baz)
```

My expectation would be:

```elisp
(foo bar
|
     baz)
;; call `puni-kill-line'
(foo bar
|    baz)
```

[This code](https://github.com/AmaiKinono/puni/blob/a559c4fc1b2504c46406f88179a72f153dd216cd/puni.el#L1637-L1643) makes it look quite deliberate, but I don't see any good rationale for this behavior. It's neither consistent with the stock Emacs, nor useful in any common workflow I can think of. On the contrary, it seems to actively disrupt my workflow.

After investigating with `git blame`, I've found [this commit](https://github.com/AmaiKinono/puni/commit/c39a4d9cc70b90a7e569f32cf42b114d8239c550). Is this possible this part is just a remnant of an older functionality that's no longer supported and should be removed?

This behavior is consistent in every major mode I've tried. Removing the indicated expression seems to fix it, but I don't know `puni` well enough to tell if it's intended after all or if there are any edge cases to consider.

**Comment by AmaiKinono** [comment]
Sorry for the late response.

> [This code](https://github.com/AmaiKinono/puni/blob/a559c4fc1b2504c46406f88179a72f153dd216cd/puni.el#L1637-L1643) makes it look quite deliberate, but I don't see any good rationale for this behavior. It's neither consistent with the stock Emacs, nor useful in any common workflow I can think of.

It is actually useful for me. See the discussion in https://github.com/AmaiKinono/puni/issues/16

Now i know there are people who likes and dislikes the behavior (thank you). I'll think about how to make both happy.

The solution proposed [here](https://github.com/AmaiKinono/puni/issues/16#issuecomment-1335848183) seems to do a good job:

```lisp
(define-advice puni-kill-line (:before (&rest _))
  "Go back to indentation before killing the line if it makes sense to."
  (when (looking-back "^[[:space:]]*")
    (back-to-indentation)))
```

**Comment by hrehfeld** [comment]
I also think the behavior is quite annoying :+1: . How do I disable it if the advice wont work?

**Comment by vifon** [comment]
If you're willing to edit the copy of `puni` on your disk, you can apply this commit: https://github.com/vifon/puni/commit/c3dbebc8b007691c36d1b1c89f71292c410feca4

**Comment by AmaiKinono** [comment]
I've redesigned the behavior to (hopefully) make everyone happy. Feel free to reopen this if you still find it inconvenient.
