### ISSUE TITLE
`puni-kill-active-region` and rectangles

### ISSUE THREAD

**Issue by okamsn** [AmaiKinono/puni#46]
When `puni-kill-active-region` is used instead of `kill-region`, the binding `C-w` can no longer be used to cut rectangles.

I think that in `puni-delete-region`, the call to `kill-region` needs to include the optional third argument. The doc string for `kill-region` says that the third argument is always non-nil when used interactively. Providing the argument makes `puni-kill-region` work with rectangles, but I haven't used the package enough to say whether that breaks something else.

```elisp
  (defun puni-delete-region (pt1 pt2 &optional kill)
    "Delete the region between PT1 and PT2.
When KILL is non-nil, also save it to kill ring.

Return t if success."
    ;; `kill-region' and `delete-region' signal errors when they fail.
    (if kill
        (kill-region pt1 pt2 t) ; <- Possible fix
      (delete-region pt1 pt2))
    t)
```

This is on Emacs 28.

**Comment by AmaiKinono** [comment]
Thanks for the report. I think recent commits should already fixed the problem, at least `puni-kill-active-region` kills rectangular region on my side. Maybe update Puni and try again?

**Comment by okamsn** [comment]
Yes, those changes fixed it. Sorry for the noise.
