### ISSUE TITLE
Sexp movement broken in nXML mode

### ISSUE THREAD

**Issue by viliaapro** [AmaiKinono/puni#50]
Hi,
I'm getting whitespace-dependent behaviour in Puni 20230214.1156, Emacs 29.0.90 in nXML mode. To illustrate, take the following:

```
<?xml version="1.0" encoding="utf-8"?>
<root>
  <a>
    foo
    <b>trapped</b>
    bar
    <c> free </c>
    baz
  </a>
</root>
```

Here, `puni-forward-sexp` and `puni-backward-sexp` exhibit broken behaviour, deviating from nXML mode's native `forward-sexp` and `backward-sexp`: effectively, Puni considers `<b>trapped</b>` to be a monolithic sexp: with point in the middle of `trapped`, sexp movements move to the end and beginning of `<b>trapped</b>`.

**Comment by viliaapro** [comment]
The culprits are `puni--strict-primitive-forward-sexp` and `puni--strict-primitive-backward-sexp`, a couple of hairy functions.

What would be the way forward? I trust nXML mode, like Lisp mode, should be pretty clean in itself and not in need of much of the magic found in these functions. Rather than hacking the magic, maybe just a little parameterization room for major modes is needed: at least an option for Puni not to do any magic.

In its basic principles, Puni seems to have the right approach. A couple of variables for mode hooks to set could be just right.

I'll try to use Emacs's `advice` functionality.

**Comment by viliaapro** [comment]
I did
```
(defun my-backward (oldfun)
  (if (eq major-mode 'nxml-mode)
      (condition-case nil
	  (nxml-backward-single-balanced-item)
	(error nil))
    (funcall oldfun)))

(advice-add 'puni--strict-primitive-backward-sexp :around
	    #'my-backward)

(defun my-forward (oldfun)
  (if (eq major-mode 'nxml-mode)
      (condition-case nil
	  (nxml-forward-single-balanced-item)
	(error nil))
    (funcall oldfun)))

(advice-add 'puni--strict-primitive-forward-sexp :around
	    #'my-forward)
```

but now slurping does funny things with newlines.

**Comment by AmaiKinono** [comment]
The real problem is `forward-symbol` is not behaving right in `nxml-mode`:

``` xml
<a>|foo</a>
;; M-x forward-symbol RET
<a>foo</a>|
```

If we inspect the `<`, `/` and `>` chars using `describe-char`, we notice they all have the "symbol" syntax, which causes the problem.

> maybe just a little parameterization room for major modes is needed: at least a switch for Puni not to do any magic.

This is a nice feature for our users, but I suspect whether it could be done. At the end, even if some major modes seems to "do the right things", they behave different from each other in subtle ways, e.g., when dealing with comments, blanks...

I'll try to find a way to fix this.

**Comment by viliaapro** [comment]
Thanks for looking into the issue!

Coincidentally, I just put my own Paredit replacement on Codeberg:

https://codeberg.org/vilij/slurpbarf-elcute

It's a pair of modes that work in Lisp Data and nXML modes. Slurpbarf mostly works in C mode and similar ones, too, but Elcute, the one doing the killing, only works in Lisp Data and nXML.

They're quite concise, so you might want to take a look and maybe give a comment. They're not on MELPA yet, as I haven't got around to it.

**Comment by AmaiKinono** [comment]
Should be fixed. Please test.

**Comment by viliaapro** [comment]
Yeah, it works!
