### ISSUE TITLE
Use puni--maybe-blink-region in puny-splice.

### ISSUE THREAD

**Issue by hsgrott** [AmaiKinono/puni#57]
Hi,

First of all, thanks for this package.

Regarding this report, puny-splice does not use puny--maybe-blink-region, so it is not possible to disable the blinking behavior when the command is invoked. Is it possible to add a specific variable to disable the effect, or to honor puny-blink-for-slurp-barf?

Best regards.

**Comment by AmaiKinono** [comment]
It's fixed and the option is renamed to `puni-blink-for-sexp-manipulating`.
