### ISSUE TITLE
Unexpected behavior of `yank` after `puni-kill-line`

### ISSUE THREAD

**Issue by roife** [AmaiKinono/puni#60]
A similar issue to the one reported in #44 has been observed in the `puni-kill-line` function, resulting in unexpected behavior when yanking from the kill-ring.

```
;; Original code
(foo |(foo
       bar) baz))
```

after calling `puni-kill-line`

```
;; Original code
(foo |baz))
```

After executing the puni-kill-line function, two items are saved into the kill-ring:

1. `(foo...bar)`
2. The space between `bar)` and `baz`

When using the yank command subsequent to `puni-kill-line`, the space is yanked instead of the expected `(foo ... bar)`. However, the expected behavior is for the yank command to paste `(foo ... bar)` from the kill-ring after executing `puni-kill-line`.

Possible Solutions:

1. Combining theses two items when killing line
2. Not to save the second item(i.e. spaces) into kill-ring
3. Introducing a new command that similar to `puni-kill-line` but not kill the redundant spaces

If any of the solutions above is adopted, I'm glad to submit a PR.

**Comment by AmaiKinono** [comment]
Fixed. I've chose the 2nd option as it seems to be more rational.
