### ISSUE TITLE
Right paren is removed when remove semi-colon in lisp-interaction-mode

### ISSUE THREAD

**Issue by conao3** [AmaiKinono/puni#65]
In `lisp-interaction-mode` or something lisp like major-mode, when I remove semi-colon, puni also remove trailing right paren.
Due to this behavior, paren balance become broken.

### repro step

1. Save below file as `~/.debug.emacs.d/puni/init.el`
```elisp
(prog1 "leaf"
  (custom-set-variables
   '(package-archives '(("melpa" . "https://melpa.org/packages/")
                        ("gnu"   . "https://elpa.gnu.org/packages/"))))
  (package-initialize)
  (use-package leaf :ensure t))

(leaf puni
  :ensure t
  :global-minor-mode electric-pair-mode puni-global-mode)
```

2. Load this init.el via `emacs --init-directory ~/.debug.emacs.d/puni`

3. Switch buffer to `*scratch*`

4. Type and occur issue. (`|` is cursor)

```elisp
;; type it
(a (b|))

;; type ;
(a (b;|))

;; backspace to remove ;
(a (b|

;; and you can see, right trailing paren is removed too.
```

**Comment by conao3** [comment]
It seems this issue comes from this code but I cannot figure out how to handle this.

https://github.com/AmaiKinono/puni/blob/72e091ef30e0c9299dbcd0bc4669ab9bb8fb6e47/puni.el#L1591-L1595

**Comment by brongulus** [comment]
Seeing the same behavior, it's very annoying when you accidentally type a semi-colon and it removes evrything following it on deletion.

**Comment by conao3** [comment]
Confirmed. thanks!!
